[package]
name = "easy-games/chickynoid"
description = "A server-authoritative networking character controller for Roblox"
license = "MIT"
authors = ["MrChickenRocket"]
version = "0.1.0"

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["wally.toml", "build.project.json", "src"]

[dependencies]
